import type { ScanResult } from '../types.js';

/**
 * Generate SUMMARY.md — the primary file for AI agent consumption.
 *
 * Budget: dense and actionable. Observations go to JSON only.
 * Sections ordered by value to agents:
 *   1. Key Files (what matters most)
 *   2. Key Relationships (what changes together)
 *   3. Rules (MUST)
 *   4. Conventions (SHOULD, top 15)
 *   5. Critical Paths
 *   6. Modules table
 *   7. Agent instructions
 */
export function generateMarkdown(result: ScanResult): string {
  const lines: string[] = [];

  lines.push('# Architecture Map');
  lines.push('');
  lines.push(`> Auto-generated by archmap v${result.manifest.version}. Do not edit manually.`);
  lines.push(`> ${result.stats.totalFiles} files | ${result.stats.totalModules} modules | Health: ${result.health.overall}/100`);

  if (result.stats.parsing) {
    const p = result.stats.parsing;
    const label = p.pct === 100 ? 'Parsing: 100% AST' : `Parsing: ${p.pct}% AST (${p.regex} regex fallback)`;
    lines.push(`> ${label}`);
    if (p.regexFiles?.length > 0) {
      lines.push(`> Regex files: ${p.regexFiles.map((f) => `\`${f}\``).join(', ')}`);
    }
  }
  lines.push('');

  // Key Files
  if (result.hotFiles?.length > 0) {
    lines.push('## Key Files');
    lines.push('');
    lines.push('| File | Risk | Fan-in | Impact | Module |');
    lines.push('|------|------|--------|--------|--------|');
    for (const hf of result.hotFiles.slice(0, 15)) {
      lines.push(`| \`${hf.file}\` | ${hf.risk} | ${hf.fanIn} | ${hf.transitiveImpact} | ${hf.module} |`);
    }
    lines.push('');
  }

  // Key Relationships
  if (result.contracts.length > 0) {
    lines.push('## Key Relationships');
    lines.push('');
    lines.push('| When you edit... | Also check... | Confidence | Co-changes |');
    lines.push('|-----------------|---------------|-----------|------------|');
    for (const c of result.contracts.slice(0, 20)) {
      lines.push(`| \`${c.entities[0]}\` | \`${c.entities[1]}\` | ${Math.round(c.confidence * 100)}% | ${c.occurrences} |`);
    }
    lines.push('');
  }

  // Critical Paths
  if (result.criticalPaths?.length > 0) {
    lines.push('## Critical Paths');
    lines.push('');
    for (const path of result.criticalPaths.slice(0, 5)) {
      lines.push(`- **${path.length} files**: \`${path.rootFile}\` → ... → \`${path.leafFile}\``);
    }
    lines.push('');
  }

  // Rules (MUST)
  const strongRules = result.rules.filter((r) => r.tier === 'rule').sort((a, b) => b.confidence - a.confidence);
  if (strongRules.length > 0) {
    lines.push('## Rules (MUST respect)');
    lines.push('');
    for (const rule of strongRules) {
      lines.push(`- **${rule.description}** (${rule.source === 'manual' ? 'team-defined' : Math.round(rule.confidence * 100) + '%'})`);
      lines.push(`  - ${rule.action}`);
    }
    lines.push('');
  }

  // Conventions (top 15)
  const conventions = result.rules.filter((r) => r.tier === 'convention').sort((a, b) => b.confidence - a.confidence).slice(0, 15);
  if (conventions.length > 0) {
    lines.push('## Conventions (SHOULD follow)');
    lines.push('');
    for (const rule of conventions) {
      lines.push(`- [${Math.round(rule.confidence * 100)}%] ${rule.description}`);
    }
    lines.push('');
  }

  // Modules table
  if (result.modules.length > 0) {
    lines.push('## Modules');
    lines.push('');
    lines.push('| Module | Language | Exports | Deps | Files |');
    lines.push('|--------|----------|---------|------|-------|');
    for (const mod of result.modules) {
      lines.push(`| \`${mod.id}\` | ${mod.language} | ${mod.publicApi.exports.length} | ${mod.internalDependencies.length} | ${mod.files.length} |`);
    }
    lines.push('');
  }

  // Agent instructions
  lines.push('## For AI Agents');
  lines.push('');
  lines.push('1. **Key Files**: High-risk files need extra care when editing');
  lines.push('2. **Key Relationships**: Check co-change partners before committing');
  lines.push('3. **Rules**: MUST respect. **Conventions**: SHOULD follow unless justified');
  lines.push('4. **Critical Paths**: Root file changes cascade — review the full chain');
  lines.push('5. Full data in `.archmap/*.json` (observations, per-file risk, all rules)');
  lines.push('');

  return lines.join('\n');
}
