import type { ScanResult, ModuleInfo, ArchRule, ImplicitContract } from '../types.js';

/**
 * Generate SUMMARY.md — the primary file for AI agent consumption.
 * Must be concise (<2000 tokens for medium projects) and information-dense.
 */
export function generateMarkdown(result: ScanResult): string {
  const lines: string[] = [];

  lines.push('# Architecture Map');
  lines.push('');
  lines.push(`> Auto-generated by archmap v${result.manifest.version}. Do not edit manually.`);
  lines.push(`> Last updated: ${result.manifest.generatedAt} | ${result.stats.totalFiles} files | ${result.stats.totalModules} modules`);
  lines.push('');

  // Module overview table
  if (result.modules.length > 0) {
    lines.push('## Modules');
    lines.push('');
    lines.push('| Module | Language | Public Exports | Internal Deps | External Deps |');
    lines.push('|--------|----------|---------------|---------------|---------------|');

    for (const mod of result.modules) {
      const exports = mod.publicApi.exports.length;
      const intDeps = mod.internalDependencies.length;
      const extDeps = mod.externalDependencies.length;
      lines.push(
        `| \`${mod.id}\` | ${mod.language} | ${exports} | ${intDeps} | ${extDeps} |`,
      );
    }
    lines.push('');
  }

  // Dependency layers
  if (result.dependencies.layers.length > 0) {
    lines.push('## Dependency Layers');
    lines.push('');
    for (let i = 0; i < result.dependencies.layers.length; i++) {
      const layer = result.dependencies.layers[i];
      const moduleNames = layer.modules.map((m) => `\`${m}\``).join(', ');
      lines.push(`${i + 1}. **${layer.name}:** ${moduleNames}`);
    }
    lines.push('');
  }

  // High-confidence rules
  const highRules = result.rules
    .filter((r) => r.confidence >= 0.8)
    .sort((a, b) => b.confidence - a.confidence)
    .slice(0, 10);

  if (highRules.length > 0) {
    lines.push('## Architectural Rules');
    lines.push('');
    for (const rule of highRules) {
      const pct = Math.round(rule.confidence * 100);
      lines.push(`- **[${pct}%]** ${rule.description}`);
    }
    lines.push('');
  }

  // Implicit contracts
  const topContracts = result.contracts
    .sort((a, b) => b.confidence - a.confidence)
    .slice(0, 10);

  if (topContracts.length > 0) {
    lines.push('## Implicit Contracts');
    lines.push('');
    for (const contract of topContracts) {
      lines.push(`- ${contract.description} (${contract.occurrences} co-changes)`);
    }
    lines.push('');
  }

  // Module details (public API)
  if (result.modules.length > 0) {
    lines.push('## Module Public APIs');
    lines.push('');
    for (const mod of result.modules) {
      if (mod.publicApi.exports.length === 0) continue;
      lines.push(`### \`${mod.id}\``);
      for (const exp of mod.publicApi.exports.slice(0, 15)) {
        lines.push(`- \`${exp.name}\` (${exp.type})`);
      }
      if (mod.publicApi.exports.length > 15) {
        lines.push(`- ... and ${mod.publicApi.exports.length - 15} more`);
      }
      lines.push('');
    }
  }

  // AI agent instructions
  lines.push('## For AI Agents');
  lines.push('');
  lines.push('When modifying this codebase:');
  lines.push('1. Check which module you are working in using the table above');
  lines.push('2. Only use the PUBLIC API of other modules (listed in Module Public APIs)');
  lines.push('3. Follow the architectural rules listed above');
  lines.push('4. If you modify a file listed in Implicit Contracts, check if the paired file needs changes too');
  lines.push('5. See `.archmap/*.json` for full structured data');
  lines.push('');

  return lines.join('\n');
}
