import type { ScanResult } from '../types.js';

/**
 * Generate SUMMARY.md — the primary file for AI agent consumption.
 * Organized by rule tier for clear actionability.
 */
export function generateMarkdown(result: ScanResult): string {
  const lines: string[] = [];

  lines.push('# Architecture Map');
  lines.push('');
  lines.push(`> Auto-generated by archmap v${result.manifest.version}. Do not edit manually.`);
  lines.push(`> Last updated: ${result.manifest.generatedAt} | ${result.stats.totalFiles} files | ${result.stats.totalModules} modules`);

  // Health score
  if (result.health) {
    const h = result.health;
    const emoji = h.overall >= 90 ? 'A+' : h.overall >= 80 ? 'A' : h.overall >= 70 ? 'B' : h.overall >= 60 ? 'C' : 'D';
    lines.push(`> Health: **${emoji}** (${h.overall}/100) | ${h.breakdown.rules.total} rules, ${h.breakdown.conventions.total} conventions, ${h.breakdown.observations.total} observations`);
  }
  lines.push('');

  // Module overview
  if (result.modules.length > 0) {
    lines.push('## Modules');
    lines.push('');
    lines.push('| Module | Language | Public Exports | Internal Deps | External Deps |');
    lines.push('|--------|----------|---------------|---------------|---------------|');
    for (const mod of result.modules) {
      lines.push(`| \`${mod.id}\` | ${mod.language} | ${mod.publicApi.exports.length} | ${mod.internalDependencies.length} | ${mod.externalDependencies.length} |`);
    }
    lines.push('');
  }

  // Layers
  if (result.dependencies.layers.length > 0) {
    lines.push('## Dependency Layers');
    lines.push('');
    for (let i = 0; i < result.dependencies.layers.length; i++) {
      const layer = result.dependencies.layers[i];
      lines.push(`${i + 1}. **${layer.name}:** ${layer.modules.map((m) => `\`${m}\``).join(', ')}`);
    }
    lines.push('');
  }

  // Rules (tier: rule) — MUST respect
  const strongRules = result.rules.filter((r) => r.tier === 'rule').sort((a, b) => b.confidence - a.confidence);
  if (strongRules.length > 0) {
    lines.push('## Rules (MUST respect)');
    lines.push('');
    for (const rule of strongRules) {
      const src = rule.source === 'manual' ? '(team-defined)' : `(${Math.round(rule.confidence * 100)}%)`;
      lines.push(`- **${rule.description}** ${src}`);
      lines.push(`  - Action: ${rule.action}`);
    }
    lines.push('');
  }

  // Conventions (tier: convention) — SHOULD follow
  const conventions = result.rules.filter((r) => r.tier === 'convention').sort((a, b) => b.confidence - a.confidence).slice(0, 15);
  if (conventions.length > 0) {
    lines.push('## Conventions (SHOULD follow)');
    lines.push('');
    for (const rule of conventions) {
      lines.push(`- **[${Math.round(rule.confidence * 100)}%]** ${rule.description}`);
      lines.push(`  - ${rule.action}`);
    }
    lines.push('');
  }

  // Observations (tier: observation) — informational
  const observations = result.rules.filter((r) => r.tier === 'observation').sort((a, b) => b.confidence - a.confidence).slice(0, 10);
  if (observations.length > 0) {
    lines.push('## Observations (informational)');
    lines.push('');
    for (const obs of observations) {
      lines.push(`- [${Math.round(obs.confidence * 100)}%] ${obs.description}`);
    }
    lines.push('');
  }

  // Implicit contracts
  const topContracts = result.contracts.sort((a, b) => b.confidence - a.confidence).slice(0, 10);
  if (topContracts.length > 0) {
    lines.push('## Implicit Contracts');
    lines.push('');
    for (const contract of topContracts) {
      lines.push(`- ${contract.description} (${contract.occurrences} co-changes)`);
    }
    lines.push('');
  }

  // Module public APIs
  if (result.modules.length > 0) {
    lines.push('## Module Public APIs');
    lines.push('');
    for (const mod of result.modules) {
      if (mod.publicApi.exports.length === 0) continue;
      lines.push(`### \`${mod.id}\``);
      for (const exp of mod.publicApi.exports.slice(0, 15)) {
        lines.push(`- \`${exp.name}\` (${exp.type})`);
      }
      if (mod.publicApi.exports.length > 15) {
        lines.push(`- ... and ${mod.publicApi.exports.length - 15} more`);
      }
      lines.push('');
    }
  }

  // AI agent instructions
  lines.push('## For AI Agents');
  lines.push('');
  lines.push('When modifying this codebase:');
  lines.push('1. **Rules** (MUST): Never violate items in the "Rules" section above');
  lines.push('2. **Conventions** (SHOULD): Follow unless you have a specific reason not to');
  lines.push('3. **Observations** (INFO): Be aware of these patterns; check paired files if relevant');
  lines.push('4. Check which module you are working in using the Modules table');
  lines.push('5. Only use the PUBLIC API of other modules (listed in Module Public APIs)');
  lines.push('6. See `.archmap/*.json` for full structured data');
  lines.push('');

  return lines.join('\n');
}
