import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

// --- Schema v2 Types ---

interface RuleEvidence {
  firstSeen: string;
  commitsSampled: number;
  recentViolations: number;
  totalInstances: number;
  matchingInstances: number;
  details?: Record<string, unknown>;
}

interface ArchRule {
  id: string;
  category: 'boundary' | 'co-change' | 'naming' | 'layer' | 'ownership';
  tier: 'observation' | 'convention' | 'rule';
  confidence: number;
  trend: 'stable' | 'strengthening' | 'weakening' | 'broken' | 'new';
  scope: string[];
  description: string;
  action: string;
  source: 'git-history' | 'static-analysis' | 'manual';
  evidence: RuleEvidence;
}

interface ModuleInfo {
  id: string;
  name: string;
  path: string;
  language: string;
  files: string[];
  publicApi: { exports: Array<{ name: string; type: string; line: number }> };
  internalDependencies: string[];
  externalDependencies: string[];
}

interface HealthScore {
  overall: number;
  trend: string;
  breakdown: {
    observations: { total: number };
    conventions: { total: number; violations: number };
    rules: { total: number; violations: number };
  };
  moduleScores: Array<{ moduleId: string; score: number; violations: number }>;
}

interface ArchmapData {
  schemaVersion?: number;
  modules: ModuleInfo[];
  rules: ArchRule[];
  health?: HealthScore;
  parsing?: { ast: number; regex: number; pct: number };
}

const OUTPUT = vscode.window.createOutputChannel('archmap');
let archmapData: ArchmapData | null = null;
let statusBarItem: vscode.StatusBarItem;

export function activate(context: vscode.ExtensionContext) {
  OUTPUT.appendLine('archmap extension activated');

  statusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 100);
  statusBarItem.command = 'archmap.showModule';
  context.subscriptions.push(statusBarItem);

  loadArchmapData();

  context.subscriptions.push(
    vscode.commands.registerCommand('archmap.init', runInit),
    vscode.commands.registerCommand('archmap.scan', runScan),
    vscode.commands.registerCommand('archmap.showModule', showModuleQuickPick),
  );

  const modulesProvider = new ModulesTreeProvider();
  const rulesProvider = new RulesTreeProvider();
  vscode.window.registerTreeDataProvider('archmap.modules', modulesProvider);
  vscode.window.registerTreeDataProvider('archmap.rules', rulesProvider);

  vscode.workspace.onDidSaveTextDocument(() => {
    loadArchmapData();
    modulesProvider.refresh();
    rulesProvider.refresh();
  });

  vscode.window.onDidChangeActiveTextEditor(updateStatusBar);

  const hoverProvider = vscode.languages.registerHoverProvider(
    ['typescript', 'javascript', 'python', 'go', 'rust', 'java'],
    { provideHover: provideModuleHover },
  );
  context.subscriptions.push(hoverProvider);

  updateStatusBar(vscode.window.activeTextEditor);

  const watcher = vscode.workspace.createFileSystemWatcher('**/.archmap/*.json');
  watcher.onDidChange(() => {
    loadArchmapData();
    modulesProvider.refresh();
    rulesProvider.refresh();
    updateStatusBar(vscode.window.activeTextEditor);
  });
  context.subscriptions.push(watcher);
}

function getWorkspaceRoot(): string | undefined {
  return vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
}

function loadArchmapData() {
  const root = getWorkspaceRoot();
  if (!root) return;

  const archmapDir = path.join(root, '.archmap');
  if (!fs.existsSync(archmapDir)) {
    archmapData = null;
    return;
  }

  try {
    const manifest = JSON.parse(fs.readFileSync(path.join(archmapDir, 'manifest.json'), 'utf-8'));
    const modules = JSON.parse(fs.readFileSync(path.join(archmapDir, 'modules.json'), 'utf-8'));
    const rules = JSON.parse(fs.readFileSync(path.join(archmapDir, 'rules.json'), 'utf-8'));

    // Compatibility checks
    const schemaVersion = rules.schemaVersion ?? manifest.schemaVersion ?? 1;
    const coreVersion = manifest.version ?? 'unknown';

    if (schemaVersion < 2) {
      const msg = `.archmap/ uses schema v${schemaVersion} (generated by archmap ${coreVersion}). Run \`archmap scan\` to upgrade to v2.`;
      OUTPUT.appendLine(`Warning: ${msg}`);
      vscode.window.showWarningMessage(`archmap: ${msg}`);
    }

    OUTPUT.appendLine(`Core version: ${coreVersion}, schema: v${schemaVersion}`);

    archmapData = {
      schemaVersion,
      modules: modules.modules,
      rules: rules.rules,
      health: manifest.health,
      parsing: manifest.stats?.parsing,
    };

    OUTPUT.appendLine(`Loaded .archmap/: ${archmapData.modules.length} modules, ${archmapData.rules.length} rules, schema v${schemaVersion}`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    OUTPUT.appendLine(`Failed to load .archmap/: ${msg}`);
    archmapData = null;
  }
}

function findModuleForFile(filePath: string): ModuleInfo | undefined {
  if (!archmapData) return undefined;
  const root = getWorkspaceRoot();
  if (!root) return undefined;

  const relative = path.relative(root, filePath).replace(/\\/g, '/');
  return archmapData.modules.find((m) => m.files.includes(relative));
}

function updateStatusBar(editor: vscode.TextEditor | undefined) {
  if (!editor || !archmapData) {
    statusBarItem.hide();
    return;
  }

  const mod = findModuleForFile(editor.document.uri.fsPath);
  if (mod) {
    const healthLabel = archmapData.health ? ` | H:${archmapData.health.overall}` : '';
    statusBarItem.text = `$(symbol-structure) ${mod.name} (${mod.publicApi.exports.length} exp, ${mod.internalDependencies.length} dep)${healthLabel}`;

    const modHealth = archmapData.health?.moduleScores.find((ms) => ms.moduleId === mod.id);
    const healthTip = modHealth ? `\nModule health: ${modHealth.score}/100 (${modHealth.violations} violations)` : '';
    const parsingTip = archmapData.parsing ? `\nParsing: ${archmapData.parsing.pct}% AST` : '';
    statusBarItem.tooltip = `Module: ${mod.id}\nLanguage: ${mod.language}\nFiles: ${mod.files.length}\nDeps: ${mod.internalDependencies.join(', ') || 'none'}${healthTip}${parsingTip}`;
    statusBarItem.show();
  } else {
    statusBarItem.hide();
  }
}

function provideModuleHover(
  document: vscode.TextDocument,
  position: vscode.Position,
): vscode.Hover | undefined {
  if (!archmapData) return undefined;

  const mod = findModuleForFile(document.uri.fsPath);
  if (!mod) return undefined;

  const wordRange = document.getWordRangeAtPosition(position);
  if (!wordRange) return undefined;
  const word = document.getText(wordRange);

  for (const m of archmapData.modules) {
    const exp = m.publicApi.exports.find((e) => e.name === word);
    if (exp && m.id !== mod.id) {
      const md = new vscode.MarkdownString();
      md.appendMarkdown(`**archmap** | Module: \`${m.id}\`\n\n`);
      md.appendMarkdown(`- Type: \`${exp.type}\`\n`);
      md.appendMarkdown(`- Defined in: \`${m.id}\` (line ${exp.line})\n`);
      if (m.internalDependencies.length > 0) {
        md.appendMarkdown(`- Module deps: ${m.internalDependencies.map((d) => `\`${d}\``).join(', ')}\n`);
      }
      return new vscode.Hover(md, wordRange);
    }
  }

  return undefined;
}

async function runInit() {
  const root = getWorkspaceRoot();
  if (!root) { vscode.window.showErrorMessage('No workspace folder open.'); return; }
  const terminal = vscode.window.createTerminal('archmap');
  terminal.show();
  terminal.sendText(`npx archmap init --root "${root}"`);
}

async function runScan() {
  const root = getWorkspaceRoot();
  if (!root) return;
  const terminal = vscode.window.createTerminal('archmap');
  terminal.show();
  terminal.sendText(`npx archmap scan --root "${root}"`);
}

async function showModuleQuickPick() {
  if (!archmapData) {
    vscode.window.showWarningMessage('No .archmap/ found. Run "archmap: Initialize" first.');
    return;
  }

  const items = archmapData.modules.map((m) => ({
    label: m.name,
    description: `${m.publicApi.exports.length} exports, ${m.internalDependencies.length} deps`,
    detail: `${m.language} | ${m.files.length} files | deps: ${m.internalDependencies.join(', ') || 'none'}`,
    module: m,
  }));

  const selected = await vscode.window.showQuickPick(items, { placeHolder: 'Select a module' });
  if (selected?.module.files.length) {
    const doc = await vscode.workspace.openTextDocument(path.join(getWorkspaceRoot()!, selected.module.files[0]));
    vscode.window.showTextDocument(doc);
  }
}

// --- Tree View: Modules ---

class ModulesTreeProvider implements vscode.TreeDataProvider<vscode.TreeItem> {
  private _onDidChangeTreeData = new vscode.EventEmitter<vscode.TreeItem | undefined>();
  readonly onDidChangeTreeData = this._onDidChangeTreeData.event;

  refresh() { this._onDidChangeTreeData.fire(undefined); }
  getTreeItem(element: vscode.TreeItem): vscode.TreeItem { return element; }

  getChildren(element?: vscode.TreeItem): vscode.TreeItem[] {
    if (!archmapData) return [];
    if (element) return [];

    // Header with health
    const items: vscode.TreeItem[] = [];
    if (archmapData.health) {
      const h = archmapData.health;
      const header = new vscode.TreeItem(`Health: ${h.overall}/100 (${h.trend})`);
      header.iconPath = new vscode.ThemeIcon(h.overall >= 80 ? 'pass' : h.overall >= 60 ? 'warning' : 'error');
      items.push(header);
    }

    for (const m of archmapData.modules) {
      const modHealth = archmapData.health?.moduleScores.find((ms) => ms.moduleId === m.id);
      const healthSuffix = modHealth ? ` [${modHealth.score}]` : '';
      const item = new vscode.TreeItem(`${m.name}${healthSuffix}`);
      item.description = `${m.publicApi.exports.length} exp, ${m.internalDependencies.length} dep`;
      item.iconPath = new vscode.ThemeIcon('symbol-module');
      item.tooltip = `${m.id}\n${m.language} | ${m.files.length} files`;
      items.push(item);
    }

    return items;
  }
}

// --- Tree View: Rules (grouped by tier) ---

class RulesTreeProvider implements vscode.TreeDataProvider<vscode.TreeItem> {
  private _onDidChangeTreeData = new vscode.EventEmitter<vscode.TreeItem | undefined>();
  readonly onDidChangeTreeData = this._onDidChangeTreeData.event;

  refresh() { this._onDidChangeTreeData.fire(undefined); }
  getTreeItem(element: vscode.TreeItem): vscode.TreeItem { return element; }

  getChildren(element?: vscode.TreeItem): vscode.TreeItem[] {
    if (!archmapData) return [];

    // Parsing stats header
    const items: vscode.TreeItem[] = [];
    if (archmapData.parsing) {
      const p = archmapData.parsing;
      const label = p.pct === 100 ? `Parsing: 100% AST` : `Parsing: ${p.pct}% AST (${p.regex} regex)`;
      const pi = new vscode.TreeItem(label);
      pi.iconPath = new vscode.ThemeIcon(p.pct === 100 ? 'pass' : p.pct >= 80 ? 'warning' : 'error');
      items.push(pi);
    }

    const tiers: Array<{ tier: 'rule' | 'convention' | 'observation'; label: string; icon: string }> = [
      { tier: 'rule', label: 'Rules (MUST)', icon: 'error' },
      { tier: 'convention', label: 'Conventions (SHOULD)', icon: 'warning' },
      { tier: 'observation', label: 'Observations (INFO)', icon: 'info' },
    ];

    for (const { tier, label, icon } of tiers) {
      const tierRules = archmapData.rules
        .filter((r) => r.tier === tier)
        .sort((a, b) => b.confidence - a.confidence)
        .slice(0, 15);

      if (tierRules.length === 0) continue;

      const header = new vscode.TreeItem(`${label} (${tierRules.length})`);
      header.iconPath = new vscode.ThemeIcon(icon);
      items.push(header);

      for (const rule of tierRules) {
        const pct = Math.round(rule.confidence * 100);
        const trendIcon = rule.trend === 'strengthening' ? '↗' : rule.trend === 'weakening' ? '↘' : rule.trend === 'broken' ? '↓' : rule.trend === 'new' ? '★' : '';
        const item = new vscode.TreeItem(`  ${trendIcon} [${pct}%] ${rule.description}`);
        item.iconPath = new vscode.ThemeIcon(
          rule.category === 'boundary' ? 'shield' :
          rule.category === 'naming' ? 'symbol-text' :
          rule.category === 'layer' ? 'layers' :
          rule.category === 'co-change' ? 'git-compare' : 'info',
        );
        item.tooltip = [
          `Category: ${rule.category}`,
          `Tier: ${rule.tier}`,
          `Confidence: ${pct}%`,
          `Trend: ${rule.trend}`,
          `Source: ${rule.source}`,
          `Scope: ${rule.scope.join(', ')}`,
          '',
          `Action: ${rule.action}`,
        ].join('\n');
        items.push(item);
      }
    }

    return items;
  }
}

export function deactivate() {
  OUTPUT.dispose();
}
