/**
 * Schema contract between archmap core and consumers (VS Code extension, MCP, etc).
 *
 * IMPORTANT: When changing this file, bump SCHEMA_VERSION.
 * Consumers check this to detect incompatibility.
 */

export const SCHEMA_VERSION = 2;

/**
 * Minimum core version this schema is compatible with.
 * Extension uses this to warn users when .archmap/ was generated by an old version.
 */
export const MIN_COMPATIBLE_CORE = '0.8.0';
